### ISSUE TITLE
Parse() Exception

### ISSUE THREAD

**Issue by friendlytomato** [selbetar/askfmArchiver#11]
Am I doing something wrong here? 

dotnet askfmArchiver.dll -u 'username' -t parse

Parse() Exception:
Object reference not set to an instance of an object.
   at askfmArchiver.Parser.GetAnswerCount(HtmlDocument html)
   at askfmArchiver.Parser.ParsePage(HtmlDocument html)
   at askfmArchiver.Parser.Parse()
Attempting to commit 0 parsed answers...

**Comment by selbetar** [comment]
It's failing due to the parser being outdated. Release [v2.1.0](https://github.com/selbetar/askfmArchiver/releases/tag/v2.1.0) has been published which should fix this issue. Make sure to re-read the [README](https://github.com/selbetar/askfmArchiver#readme) as the commands have changed a bit.
