### ISSUE TITLE
Nothing to generate

### ISSUE THREAD

**Issue by Mewgood** [selbetar/askfmArchiver#2]
Hi,
Trying to execute by running:
`dotnet askfmArchiver.dll -u 'username' -t 'markdown'`

Output:
Nothing to generate

Any ideas?

**Comment by selbetar** [comment]
That means there are no records in the database for the specified user which indicates that you haven't run an archival job yet by executing `dotnet askfmArchiver.dll -u 'username' -t 'parse'`.

Or, there are records in the database for the specified user, but you have already generated the markdown files once before. This is expected since the tool checks to see if a markdown job has been executed before and will only generate files that contain answers newer than the answers included in the previous job.

**Comment by Mewgood** [comment]
Yeah, I figured it out, sort of. However, more specifically the error is due to this:
`Progress: 76,47%   Parse() Exception: 
Input string was not in a correct format.
Attempting to commit 2275 parsed answers...`

Can you maybe issue an update that includes the specific string, so that I can tell what is causing this exception?

**Comment by selbetar** [comment]
I've issued an update and published a new release. It should fix the issue, but if it occurs again then please report the error, it should be more verbose now.

**Comment by Mewgood** [comment]
Parsing error is gone now. Nice! :)

But executing with markdown parameter doesn't generate any files. Log says:
`Parse() Exception: 
Object reference not set to an instance of an object.
   at askfmArchiver.Parser.GetAnswerCount(HtmlDocument html) in /home/qaedus/MyFiles/Projects/github/askfmArchiver/askfmArchiver/Parser.cs:line 368
   at askfmArchiver.Parser.ParsePage(HtmlDocument html) in /home/qaedus/MyFiles/Projects/github/askfmArchiver/askfmArchiver/Parser.cs:line 100
   at askfmArchiver.Parser.Parse() in /home/qaedus/MyFiles/Projects/github/askfmArchiver/askfmArchiver/Parser.cs:line 73Attempting to commit 0 parsed answers...`

Btw, awesome tool. Wanted to make something like this, but the languages I know doesn't fit this type of project. A lot of work to do this in C or C++, which are my primary languages.

**Comment by selbetar** [comment]
Looks like a parsing error, make sure to remove `'parse'` from the arguments when you are generating the markdown file.

**Comment by Mewgood** [comment]
I did, but the output is just "Nothing to generate". Sorry for the trouble, hope it's ok.

**Comment by selbetar** [comment]
If you haven't specified an output folder using the `-o` flag then please check the directory of the tool for a folder called `output`, any output will be there. If nothing is there, then please do the following if you have sqlite installed. 

```
sqlite3 data.db
select count(*) from answers where userid = "USERNAME";
select stopat from pdfgen where userid = "USERNAME";
``` 
If the first statement reports 0, it means there's no records with username **USERNAME**.
run
`dotnet askfmArchiver.dll -u 'username' -t parse`

If the second statement doesn't show `1/1/0001 12:00:00 AM` then it means the markdown files have been generated once before. If that's the case then do the following:
```
update pdfgen set stopat="1/1/0001 12:00:00 AM"  where userid = "USERNAME";
.quit
```
and re-run
`dotnet askfmArchiver.dll -u 'username' -t markdown`

If this somehow doesn't fix the issue and no errors are reported then I'm not really sure what is wrong as I can't reproduce this issue.

**Comment by Mewgood** [comment]
Thanks for the reply, but I figured it out after trying a few times more.

It’s because it’s case sensitive when passing markdown argument 😄

**Comment by selbetar** [comment]
Thanks for reporting back, the new release resolves this issue.
