### ISSUE TITLE
What to do after making the markdown file?

### ISSUE THREAD

**Issue by AliJR00** [selbetar/askfmArchiver#3]
Could you please tell me what to do in detail?
I have been struggling for 3 hours now and I couldn't do anything. :""(
Thanks in advance

**Comment by selbetar** [comment]
If you want to convert the markdown to pdf/html then you can use any tool that supports such conversion.

There are multiple tools out there, but I would recommend using `visual studio code` with the extension [yzane/vscode-markdown-pdf](https://github.com/yzane/vscode-markdown-pdf) if you don't want to convert it programmatically. Refer to the `README` of that project to learn how to use it.

**Comment by AliJR00** [comment]
Thanks.
But why the file starts with the oldest questions first?

**Comment by selbetar** [comment]
Happens to work better for me. I might add more options in the future for the user to determine the order of the output if someone wants it, so feel free to submit a PR or a feature request.

Marking this issue as resolved.
