### ISSUE TITLE
Parse() Exception: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Mewgood** [selbetar/askfmArchiver#4]
Hi,

I'm getting this error. Worked perfectly some time ago.

Parse() Exception: 
Object reference not set to an instance of an object.
   at askfmArchiver.Parser.SetUserName(HtmlDocument html)
   at askfmArchiver.Parser.ParsePage(HtmlDocument html)
   at askfmArchiver.Parser.Parse()
Attempting to commit 0 parsed answers...

**Comment by selbetar** [comment]
The parser has been updated, which should fix this issue. Get the newest release and make sure to move your database file over to the new folder.
