### ISSUE TITLE
Dockerizing the app

### ISSUE THREAD

**Issue by Mewgood** [selbetar/askfmArchiver#7]
Hey,

Thanks for this great app!

I just wanted to ask what you guys think about dockerizing it? It would be pretty simple building a container and ssh into it and run commands. Later we could build a complete web UI, sort of like YouTubeDL docker containers.

**Comment by selbetar** [comment]
It took a while, but there's a [dockerized](https://github.com/selbetar/askfmArchiver/pkgs/container/askfmarchiver) version now.
